---
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
theme: hugo-smorg
baseURL: https://xn--abclillabegravningsbyrn-58b.se/
languageCode: sv-SE
title: ABC Lilla Begravningsbyrån
author:
  name: ABC Lilla Begravningsbyrån AB
  email: abcbegravning@gmail.com
copyright: "&copy; ABC Lilla Begravningsbyrån AB 2018, ABC Lilla begravningsbyrån
  AB, Skönviksvägen 244, 122 42 Enskede, tel 08-648 76 55"
metaDataFormat: yaml
summaryLength: 20
paginate: 2
GoogleAnalytics: UA-102282722-1
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
pygmentsCodefences: true
enableGitInfo: false
enableRobotsTXT: true
enableEmoji: false
params:
  debug: false
  favicon: true
  cssPath: css/smorg.min.css
  only_feed_summaries: true
  fullname: ABC Lilla Begravningsbyrån
  home: En Begravningsbyrån
  description: ABC Lilla begravningsbyrån i Stockholm, vi erbjuder begravning för
    lägre priser i Stockholm. En begravningsbyrå i Stockholm för dig. Vi hjälper Er
    med allt som hör begravningen till. ABC Lilla begravningsbyrån, Stockholm är en
    prisvärd billig begravningsbyrå och kan erbjuda tjänster till låg kostnad.
  logotype: <img src="img/abclogga.png">
  footer: 'Organisationsnummer: 556858-8270'
  subfooter: " "
  publisher:
    type: Organization
    name: ABC Lilla Begravningsbyrån
    logo: img/abclogga.png
menu:
  sectionmenu:
  - url: GDPR/
    name: GDPR
    parent: Om oss
    weight: 23
  - url: om-oss
    name: Om oss
    parent: Om oss
    weight: 1
  - url: om-oss/
    name: Om oss
    weight: 5
    identifier: om-oss
  - url: om-oss/begravningsbyra-bromma-vaesterort-vaellingby/
    name: 'Begravningsbyrå Bromma, Västerort, Vällingby, Södermalm, Norrmalm, Kungsholmen,
      Vasastan, Gamla stan, Östermalm, Järfälla, Spånga, Sundbyberg, Solna, Sollentuna,
      Huddinge, Ekerö, Haninge, Botkyrka, Danderyd, Lidingö, Nacka, Nynäshamn, Salem,
      Tyresö '
    parent: Om oss
    weight: 3
  - url: om-oss/rekommendationer/
    name: Rekommendationer
    parent: Om oss
    weight: 2
  - url: begravningen/
    name: Begravningen
    weight: 2
    identifier: begravningen
  - url: begravningen/begravningsform/
    name: Begravningsform
    parent: begravningen
    weight: 10
  - url: begravningen/att-se-den-doede/
    name: Att se den döde
    parent: begravningen
    weight: 11
  - url: begravningen/ceremonin/
    name: Ceremonin
    parent: begravningen
    weight: 12
  - url: begravningen/tiden-efter/
    name: Tiden efter
    parent: begravningen
    weight: 13
  - url: begravningen/kremationsbegravning/
    name: Kremationsbegravning
    parent: begravningen
    weight: 14
  - url: begravningen/vad-goer-jag-nu/
    name: Vad gör jag nu?
    parent: begravningen
    weight: 15
  - url: begravningen/doedsfallet/
    name: Dödsfallet
    parent: begravningen
    weight: 16
  - url: begravningen/det-praktiska/
    name: Det praktiska
    parent: begravningen
    weight: 17
  - url: kontakt/
    name: Kontakt
    weight: 1
    identifier: kontakt
  - url: kontakt/hitta-hit/
    name: Hitta hit
    parent: kontakt
    weight: 8
  - url: kontakt/kontaktformular/
    name: Kontaktformulär
    parent: kontakt
    weight: 9
  - url: priser/
    name: Priser
    weight: 3
    identifier: priser
  - url: priser/kistor/
    name: Kistor
    parent: priser
    weight: 18
  - url: priser/urnor/
    name: Urnor
    parent: priser
    weight: 19
  - url: juridik/
    name: Juridik
    weight: 4
    identifier: juridik
  - url: juridik/bouppteckningar/
    name: Bouppteckningar
    parent: juridik
    weight: 20
  - url: juridik/testamente/
    name: Testamente
    parent: juridik
    weight: 21
  - url: juridik/min-sista-vilja/
    name: Min sista vilja
    parent: juridik
    weight: 22
  - url: partners/
    name: Partners
    weight: 6
    identifier: partners
  - url: gravstenar/
    name: Gravstenar
    weight: 7
    identifier: gravstenar
mediaTypes:
  application/atom:
    suffixes: xml
outputFormats:
  Atom:
    mediaType: application/atom
    baseName: atom
  RSS:
    mediaType: application/rss
    baseName: rss
outputs:
  home:
  - HTML
  - Atom
  - RSS
