# exampleSite/config.yaml
#
# Configuration file for the demonstration of the Hugo-smorg theme,
# mobile-first, responsive theme for the Hugo static site generator.
# https://gohugo.io/

# IMPORTANT:
# themesDir is needed only to run exampleSite in-place; comment out or delete
# this line for regular theme use:
#themesDir: "../.."

# Mandatory $.Site Variables ---------------------------------------------
# Site variables are built-in to the Hugo application and can be accessed using
# the {{ $.Site.variablename }} template directive.
#
# Every site needs these few: theme, baseURL, languageCode and title
# Name of the theme your Hugo site uses; leave this in place:
theme: "hugo-smorg"
baseURL: "http://www.example.com/"
languageCode: "en-us"
title: "Hugo-Smorg Theme"

# Optional $.Site Variables ----------------------------------------------
# More info on Site variables; https://gohugo.io/getting-started/configuration/
#
# Optional variables can be edited or commented out as desired.
#
# author name appears in RSS and Atom feeds;
# author email address is optional and can be # commented out.
author:
    name: "ABC Lilla Begravningsbyr책n 2018"
    email: "thisemaildoesnotexist@www.example.com"

# copyright appears in the default site footer
copyright: "&copy; ABC Lilla Begravningsbyr책n 2018"

# metaDataFormat for new content pages generated with the `hugo new` command if
# not otherwise specified by an archetype. Hugo-Smorg theme examples all use
# the easy to understand and write YAML format.
metaDataFormat: yaml

# summaryLength limits the number of words included in auto-generated page
# summaries Manual control of summaries is possible using the <!--more-->
# directive in content files. https://gohugo.io/content-management/summaries/
summaryLength: 20

# paginate sets the maximum number of items (pages) in a page listing.
paginate: 2  # set very low for demo purposes only, 5 - 10 or more would be reasonable

# GoogleAnalytics offers deep insight into how visitors use your site. It's
# optional, and free: https://www.google.com/analytics/analytics/
# Only uncomment if you have a GA UD:
# GoogleAnalytics: # add your UA-nnn-nnnnnnnn ID and uncomment

# Disqus is a popular commenting system; to get an account visit:
# https://disqus.com/admin/create/`
# Uncommenting will result in Disqus capability extended to each blog post.
# disqusShortname: "yourdiscussshortname"

# Code oriented optional features:
# pygments variables tune code syntax highlighting features Hugo provides
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
pygmentsCodefences: true

# enableGitInfo populates a .GitInfo object for each git-managed page
# The theme does not currently make use of the information.
enableGitInfo: false

# enableRobotsTXT: <false> enables generation of site robots.txt from
# front-matter directives. Many sites may prefer to create a robots.txt file in
# the site content directory.
enableRobotsTXT: true

# enableEmoji: <false> enables Emoji rendering see:
# https://www.webpagefx.com/tools/emoji-cheat-sheet/
enableEmoji: false








# Optional Features ------------------------------------------------------

# $.Site.Params variables are user-definable; the Hugo-Smorg theme makes use of
# a number of variables to enable a certain amount of customization without
# requiring editing of templates. See `docs/customizing.md` for more
# information.

# Access in templates via $.Site.Params.somevariablename
params:
    # debug: true causes template path to be output at top of page, handy for dev
    debug: false

    # cssPath: <css/smorg.css> site main CSS; can be supplemented by including
    # link or style elements in a custom site partials/head-custom.html
    cssPath: 'css/smorg.css' # Default, override here

    # only_feed_summaries: Include only Page summaries in Atom and RSS feeds.
    only_feed_summaries: true

    # fullname: Used in head and footer partials; Atom and RSS generation.
    # JSON-LD microdata for search engines
    fullname: "ABC Lilla Begravningsbyr책n"

    # Description: Used per fullname.
    description: "160 characters or less describing you or your organization or your
                  site's purpose."

    # Sites should customize their logo or wordmark here; Provided via partials/logo.html.
    # used in default navigation and footer.
    logotype: '<img src="img/abclogga.png">'
    footer: '<a href="https://github.com/solutionroute/hugo-smorg">Hugo-smorg</a> theme by <a href="https://mikewatkins.ca/">Mike Watkins</a>'
    subfooter: 'Skapad med <a href="https://appernetic.io">Appernetic.io</a>'

    # Optional information used in RSS, Atom and JSON-LD microdata. See Schema.org.
    publisher:
        # Type must be either "Organization" or "Person"
        type: Organization
        name: ABC Lilla Begravningsbyr책n
        logo: img/abclogga.png


# Primary Navigation Menu (partials/nav.html) ----------------------------

# The exampleSite menu exploses About, Projects and Blog
# Note that "About" is added to the menu within content/about.md - it's
# not a true "section" like post and project, although you can change this.

# NOTE: Don't put leading "/" in the url parameter
menu:
    sectionmenu:
        - name: "Om oss"
          url: "om-oss/"
          identifier: "om-oss"
          weight: 20

        - name: "Kontakt"
          url: "om-oss/kontakt/"
          parent: "om-oss"
          weight: 201

        - name: "Begravningen"
          url: "begravningen/"
          identifier: "begravningen"
          weight: 10

        - name: "Begravningsformen"
          url: "begravningen/begravningsformen/"
          parent: "begravningen"
          weight: 101

        - name: "XYZ-1000"
          url: "begravningen/xyz-1000/"
          parent: "begravningen"
          weight: 102



# Syndication feeds atom.xml and rss.xml ---------------------------------
# Adds Atom feed support in conjunction with /layouts/index.atom.xml
# Change default rss filename to rss.xml, layout is built in to Hugo
mediaTypes:
  application/atom:
    suffix: xml

outputFormats:
  Atom:
    mediaType: application/atom
    baseName: atom
  RSS:
    mediaType: application/rss
    baseName: rss

outputs:
  home:
    - HTML
    - Atom
    - RSS

# Optional, disable RSS feed
#disableKinds:
  #- RSS
