---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/begravningen
  label: Begravningen
  create: all
  match: "**/*"
- type: directory
  path: content/juridik
  label: Juridik
  create: all
  match: "**/*"
- type: directory
  path: content/om-oss
  label: Om oss
  create: all
  match: "**/*"
- type: directory
  path: content/priser
  label: Priser
  create: all
  match: "**/*"
- type: directory
  path: content/gravstenar
  label: Gravstenar
  create: all
  match: "**/*"
- type: directory
  path: content/partners
  label: Partners
  create: all
  match: "**/*"
- type: directory
  path: content/kontakt
  label: Kontakt
  create: all
  match: "**/*"
upload_dir: static/images/bilder
public_path: "/images/bilder"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.104.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
